### PR TITLE
Thie commits fixes weapons being picked up backwards when looking left.

### PR DESCRIPTION
**Pull request by ETdoFresh**

### CODE REVIEW

**Comment by Tlmader** [comment]
"Fix weapons being picked up backwards when looking left" would be what I was talking about before.

Can't tell if trolling or not.

Great work as always.

**Comment by tlmader** [comment]
Hmm, it doesn't seem to be working right. It rotates it when I'm facing the correct direction.

**Comment by tlmader** [comment]
I just realized the double meaning in my comment.

**Comment by ETdoFresh** [comment]
Opened a new PR #174

**Pull request closed without merging**
