### PR TITLE
Feature/remap throw and grab controls

### PR DESCRIPTION
**Pull request by ETdoFresh**
Left Click Hold as Grab/Pickup and Right Click Hold as Throw.

### CODE REVIEW

**Comment by tlmader** [comment]
Exception on this line:
image

**Comment by tlmader** [comment]
@rac7hel can you checkout this branch and look at this?

**Comment by rac7hel** [comment]
replace that code with this:

```
        // AI stuff: Mark this enemy's position around the player as available
        float attackPosition = blackboard.GetFloatVar("attackPosition");
        if (attackPosition != -1) {
            string side = blackboard.GetStringVar ("attackSide");
            GlobalBlackboard.Instance.GetBoolVar (side + "pos" + attackPosition).Value = false;
        }
```

**Comment by ETdoFresh** [comment]
I fixed this in PR #173 fix/grab-system

**Comment by ETdoFresh** [comment]
This PR now depends on #173.

**Pull request merged**
